### ISSUE TITLE
Tricky68k sources

### ISSUE THREAD

**Issue by AbelVincze** [shysaur/Tricky68k#3]
Hi, sorry for my probably lame questions/requests, but i'm not working with xcode usually. 

I'm working on an assembly project for old 68k based macintosh computers, and tricky68k is the perfect test platform for developing, the only thing i would like to add, is a bitmap, that is showing the content of the memory (1 pixel = 1 bit, 8 horizontal pixels = 1 byte). This is why i would like to edit the sources with xCode.

Could you point me how to compile tricky68k using xCode on my Mac OS X El Capitain? I downloaded the package, but when i'm trying to compile, it reports a lot of error (some missing file, and some syntax issues). I think there should be also some additional files to download.

Thanks!

**Comment by shysaur** [comment]
Check that you also pulled all the submodules used by Tricky68k by using `git pull --recurse-submodules`.

Additionally, before the first build or after a clean, Xcode may report that there are errors due to the lack of some headers which are produced at compile time. These errors are false negatives; once you build Tricky68k for the first time they will disappear. When building, additional errors are reported by Xcode because when building the GNU linker it misinterprets the output of the makefile, but the build succeeds anyway. Again, on subsequent builds these errors will no longer be visible.

Apart from that, there are no special procedures to follow to build Tricky68k: just open the root workspace `M68kSim.xcworkspace` (not the xcodeproj files!) and then click the Build & Run toolbar button.

Good luck with your project!

**Comment by AbelVincze** [comment]
Thank You!
